### ISSUE TITLE
renew_certificate.sh failed after QNAP upgrade

### ISSUE THREAD

**Issue by grantzhou** [Yannik/qnap-letsencrypt#38] opened 2018-01-04 08:54 UTC
**Platform/Firmware Information**
```
Platform = X86_BRASWELL
DISPLAY_NAME = TS-453A
Model = TS-X53II
Internal Model = TS-X53II
Version = 4.3.4
Build Number = 20171223
Rsync Model = QNAP
Build Date = 2017-12-23
```

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
The service stopped after my last QNAP firmware upgrade.
it shall be caused by the Python environment I believe, since the SimpleHTTPServer can not be started.

================ <<<<<**env checking**
[/share/Web/qnap-letsencrypt/tmp-webroot] # python -m SimpleHTTPServer 8069
/usr/local/bin/python: No module named SimpleHTTPServer
[/share/Web/qnap-letsencrypt/tmp-webroot] # python
Python 2.7.5 (default, Dec 23 2017, 12:36:39)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[/share/Web/qnap-letsencrypt/tmp-webroot] # python -m SimpleHTTPServer 9000
/usr/local/bin/python: No module named SimpleHTTPServer
[/share/Web/qnap-letsencrypt/tmp-webroot] #
==================== **renew_certificate.sh output**
Checking whether to renew certificate on Thu, 04 Jan 2018 00:35:25 -0800
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 21779
**/usr/local/bin/python: No module named SimpleHTTPServer**
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying <MY.DOMAIN.NAME>...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/SmR<.....>LudAs, but couldn't download http://<MY.DOMAIN.NAME>/.well-known/acme-challenge/SmR<......>LudAs

**Comment by Yannik** [comment] 2018-01-04 10:36
Check that you have the correct python qpkg installed. (This seems to be the problem)

**Comment by grantzhou** [comment] 2018-01-04 19:59
Thanks Yannik, I checked the python installation on my system.
I changed the renew_certificate.sh to use the python installed by qnap app center, (/share/CACHEDEV2_DATA/.qpkg/Python/src/bin), now the renew_certificate can be executed successfully.

**Comment by thomisus** [comment] 2018-01-05 16:12
Same error, could you describe how to fix it?
I run source  /etc/profile.d/python2.bash as patch notes says but still error.

**Comment by Yannik** [comment] 2018-01-05 16:15
@thomisus What is the output of `which python` on your system?

**Comment by kasi45** [comment] 2018-01-05 16:54
@Yannik 

my suggestion
change the script "renew_certificate.sh" in your git so that the internal apache is used. 
so you can use qnap's internal Python and you don't need the Python modul "SimpleHTTPServer"

you can find my example script "renew_certificate.sh" here:
https://github.com/Yannik/qnap-letsencrypt/files/1586094/renew_certificate.sh.log

you don't have to accept all changes, only the important ones for the webserver.

sorry,  for the bad english

**Comment by thomisus** [comment] 2018-01-06 00:12
[/share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt] # which python
/usr/local/bin/python
[/share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt] # python --version
Python 2.7.5

* If i source  /etc/profile.d/python2.bash ( after installing qpkg python 2.7.12.1 )

[/share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt] # source /etc/profile.d/python2.bash
[/share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt] # which python
/usr/local/python2/bin/python
[/share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt] # python --version
Python 2.7.12

I can see that the server on port 80 starts but no file is written in  tmp-webroot/.well-known/acme-challenge/

**Comment by Yannik** [comment] 2018-01-06 11:38
@kasi45 thank you for your suggestion, I like it in general, but it won't work if the internal apache doesn't start due to an invalid certificate (vicious circle...). I'd rather try to fix the incorrect python path.

@thomisus What is the output of `find /share/ -mindepth 1 -maxdepth 2 -type d -name .qpkg` on your qnap?

**Comment by kasi45** [comment] 2018-01-07 14:54
@ Yannik,
thanks for your answer.
yesterday I installed a new qnap nas and you're right! there were problems using Apache without a valid certificate. I wasn't aware of that before.
At the same time, I realized that there is no Python 2.7. x qpkg for some NAS platforms. Only one Python 3.5 qpkg (among other things for "marvell arm") I think a good alternative is the use of "EntwareNG-QPKG". There is a work package python2.7. x for all platforms. (opkg install python). You also need "EntwareNG" on different platforms to use a new "wget". On these NAS platforms, QNAP has an old "wget"version, which does not allow downloading of "cacert. pem". The "wget" of EntwareNG has no problem with this. ""git" is also one of the packages from EntwareNG. 
Maybe "EntwareNG" is the alternative to "python qpkg"! and everything works with your QNAP Letsencrypt project!

Installing "EntwareNG"
https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS
opkg install git
opkg install python
(opkg install wget)


Translated with www.DeepL.com/Translator

**Comment by Yannik** [comment] 2018-01-07 15:40
@kasi45 Do you know which platforms do/don't provide the python2.7 qpkg?

Can you tell me more exactly what the problem with wget is on your platform?

**Comment by Yannik** [comment] 2018-01-07 15:51
@kasi45 I have just updated qnap-letsencrypt. Now it should (theoretically) work with both python2.7 and python3. Can you test this on your system?

**Comment by kasi45** [comment] 2018-01-07 16:29
@Yannik 

NAS TS-419P (Marvell ARM) Firmware 4.3.3
some time ago there was the QPKG Python 2.7. x in the AppCenter.
This is no longer available to QNAP. 
There is now only Python 3.5

wget orginal firmware Qnap:
`[~] # which wget
/usr/bin/wget
[~] # wget --no-check-certificate https://curl.haxx.se/ca/cacert.pem
--2018-01-07 16:49:54--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 151.101.114.49, 2a04:4e42:1b::561
Connecting to curl.haxx.se|151.101.114.49|:443... connected.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Unable to establish SSL connection.
[~] #`

wget EntwareNG:
`[~] # opkg install wget
Installing wget (1.18-2) to root...
Downloading http://pkg.entware.net/binaries/armv5/wget_1.18-2_armv5soft.ipk
Configuring wget.
[~] #

[~] # which wget
/opt/bin/wget

[~] # /opt/bin/wget --no-check-certificate https://curl.haxx.se/ca/cacert.pem
--2018-01-07 16:51:35--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 151.101.114.49, 2a04:4e42:1b::561
Connecting to curl.haxx.se|151.101.114.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 236061 (231K) [application/x-pem-file]
Saving to: 'cacert.pem'

cacert.pem         100%[============================================================================>] 230.53K  --.-KB/s    in 0.1s

2018-01-07 16:51:36 (1.70 MB/s) - 'cacert.pem' saved [236061/236061]
`
NAS TS-253 Pro Firmware 4.3.4
The AppCenter offers Python 2.7 and 3.5
The "wget" error is the same as on the TS-419P

Not all QNAP NAS are affected by the "wget" error. 
We have already noticed this in the German Qnapclub.
If there is an old wget on the NAS you can't recognize by the firmware version number. 
with the same version number, but different platforms, there may be different versions of wget.

**Comment by Yannik** [comment] 2018-01-07 16:39
Please try the following commands:
```
wget -v --debug --no-check-certificate https://curl.haxx.se/ca/cacert.pem
wget -v --debug --secure-protocol=TLSv1 --no-check-certificate https://curl.haxx.se/ca/cacert.pem
curl --location --remote-name --insecure https://curl.haxx.se/ca/cacert.pem
```

Does one of them work?

Can you please check if qnap-letsencrypt works with python3 on your nas.

**Comment by kasi45** [comment] 2018-01-07 16:56
wget -v --debug --no-check-certificate https://curl.haxx.se/ca/cacert.pem
Setting --check-certificate (checkcertificate) to 0
DEBUG output created by Wget 1.16 on linux-gnueabi.

--2018-01-07 17:54:38--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 151.101.114.49, 2a04:4e42:1b::561
Caching curl.haxx.se => 151.101.114.49 2a04:4e42:1b::561
Connecting to curl.haxx.se|151.101.114.49|:443... connected.
Created socket 3.
Releasing 0x00d6f748 (new refcount 1).
Initiating SSL handshake.
SSL handshake failed.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Closed fd 3
Unable to establish SSL connection.

[~] # wget -v --debug --secure-protocol=TLSv1 --no-check-certificate https://curl.haxx.se/ca/cacert.pem
Setting --secure-protocol (secureprotocol) to TLSv1
Setting --check-certificate (checkcertificate) to 0
DEBUG output created by Wget 1.16 on linux-gnueabi.

--2018-01-07 17:54:39--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 151.101.114.49, 2a04:4e42:1b::561
Caching curl.haxx.se => 151.101.114.49 2a04:4e42:1b::561
Connecting to curl.haxx.se|151.101.114.49|:443... connected.
Created socket 3.
Releasing 0x01edb760 (new refcount 1).
Initiating SSL handshake.
SSL handshake failed.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Closed fd 3
Unable to establish SSL connection.

[~] # curl --location --remote-name --insecure https://curl.haxx.se/ca/cacert.pem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  230k  100  230k    0     0   517k      0 --:--:-- --:--:-- --:--:--  539k
[~] #

**Comment by kasi45** [comment] 2018-01-07 17:25
@Yannik 
to python3:
there are two big problems!

cannot run on the console -> the "path" is not extended correctly on the console
 # export|grep PATH
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin"

the cause can be found in the file in $HOME/.bash_profile

possible solution:
"source /etc/profile.d/python3.bash"
but the second problem is the missing symlink python -> python3

**Comment by Yannik** [comment] 2018-01-07 17:30
@kasi45 
Can you use this feature please for quoting shell output: https://help.github.com/articles/creating-and-highlighting-code-blocks/

In your previous comment we can see, downloading using curl works. So I will just replace the wget commands with curl.

About the python3: It seems very stupid that there's no symlink python->python3... Oh well.

What is the content of /etc/profil.d/python3.bash?

What is the output of the following command:
```
realpath $(which python3) # after sourcing python3.bash
```

**Comment by kasi45** [comment] 2018-01-07 18:36
@Yannik 

the command "realpath" does not exist in the firmware
But this could help you:

Python2 OPKG
```
[~] # /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf
/share/CACHEDEV1_DATA/.qpkg/Python
[~] #
[~] # $(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2 -V
Python 2.7.12
[~] #
```
Python3 OPKG
```
[~] # /sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf
/share/MD0_DATA/.qpkg/Python3
[~] #
[~] # $(/sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf)/python3/bin/python3 -V
Python 3.5.0
[~] #
```
I would use a variable PYTHON and set the contents of the variable with the commands from above 
(if/elseif/else)  or something like that

**Comment by Yannik** [comment] 2018-01-07 18:39
Thank you, this seems very useful.

What is the output of `/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf` on your system with python 3.5 only?

**Comment by kasi45** [comment] 2018-01-07 18:42
nothing

**Comment by Yannik** [comment] 2018-01-07 18:45
What is the exit code? You can get it by executing `/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf; exit $?`

**Comment by Yannik** [comment] 2018-01-07 18:45
@kasi45 What is the exit code? You can get it by executing `/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf; exit $?`

**Comment by kasi45** [comment] 2018-01-07 18:54
I think you mean " /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf; echo $?"  
not "exit" -> this closed the session.

" /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf; echo $?"   if OK "0" / if not OK "250"

**Comment by Yannik** [comment] 2018-01-07 18:59
Yes I mean echo $?

**Comment by Yannik** [comment] 2018-01-07 19:41
>What is the content of /etc/profil.d/python3.bash?

**Comment by Yannik** [comment] 2018-01-07 19:41
@kasi45 
I think you missed this question: 

>What is the content of /etc/profil.d/python3.bash?

**Comment by Yannik** [comment] 2018-01-07 19:53
@kasi45 I just updated renew_certificate.sh. Can you please check if it works for you both with python2.7 and python3.5

**Comment by kasi45** [comment] 2018-01-07 19:55
@Yannik 

````
_PYTHON3_QPKG_CONF=/etc/config/qpkg.conf
_PYTHON3_QPKG_NAME="Python3"
_PYTHON3_QPKG_ROOT=$(/sbin/getcfg $_PYTHON3_QPKG_NAME Install_Path -f ${_PYTHON3_QPKG_CONF})
_PYTHON3_QPKG_BIN="${_PYTHON3_QPKG_ROOT}/python3/bin"
echo "${PATH}" | grep -q  ${_PYTHON3_QPKG_BIN} || export PATH=${_PYTHON3_QPKG_BIN}:${PATH}
````

python3 is a symlink to python3.5

I also often use getcfg / setcfg in my scripts.

**Comment by kasi45** [comment] 2018-01-07 20:15
the path to python2 is different for me 
see also in my contribution above.

$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2

**Comment by kasi45** [comment] 2018-01-07 20:31
In the" IF" construct I would first build in a test that is only aimed at "python". (successful loading of the modules)  
 when not OK, then test for python2-qpkg, then for python3-qpkd and then error message.
This also applies to the devices that use EntwareNG.

The sequence of the test can also have a different sequence than the one described above.

**Comment by Yannik** [comment] 2018-01-07 20:44
@kasi45 Ok I changed the path according to your findings. I don't have access to a qnap nas right now so I cannot check. 

For the same reason, can you create a PR for the module check?

**Comment by Yannik** [comment] 2018-01-07 20:47
@kasi45 I checked with some other reports I have previously, some people reported the path as `.qpkg/Python/bin/python`. Can you check if this also exists for you?

**Comment by kasi45** [comment] 2018-01-07 20:58
@yannik,
````
 # ls -lsa /share/CACHEDEV1_DATA/.qpkg/Python
total 240
  4 drwxr-xr-x  3 admin administrators   4096 2018-01-07 18:58 ./
  4 drwxrwxrwx 11 admin administrators   4096 2018-01-07 18:59 ../
196 -rw-r--r--  1 admin administrators 199760 2018-01-07 18:58 .list
  4 -rw-r--r--  1 admin administrators    134 2017-10-17 11:19 python2.bash
  4 -rwxr-xr-x  1 admin administrators    955 2017-10-17 11:50 python.sh*
  8 -rw-r--r--  1 admin administrators   4711 2014-08-22 14:39 .qpkg_icon_80.gif
  4 -rw-r--r--  1 admin administrators   3610 2014-08-22 14:39 .qpkg_icon.gif
  8 -rw-r--r--  1 admin administrators   4360 2014-08-22 14:39 .qpkg_icon_gray.gif
  4 drwxr-xr-x  6 admin administrators   4096 2017-10-17 11:14 src/
  4 -rwxr-xr-x  1 admin administrators    780 2018-01-07 18:58 .uninstall.sh*
[~] #
````
what does "PR" mean? 
I don't know much about python. 

you can query if the call of "$PYTHON"... /HTTPServer. py & is successful.
....
python=phyton
"$PYTHON"... /HTTPServer. py &  
if not successful do the test for python2-qpkg, then do the test for python3....
....

**Comment by kasi45** [comment] 2018-01-07 21:14
@Yannik 
Test on NAS number "3"!
OHHH!! on TS-459
````
[~] # ls -lsa /share/MD0_DATA/.qpkg/Python
   4 drwxr-xr-x    6 admin    administ      4096 Mar 25  2015 ./
   4 drwxrwxrwx   11 admin    administ      4096 Dec 18 16:09 ../
 208 -rw-r--r--    1 admin    administ    210981 Mar 30  2016 .list
   4 -rw-r--r--    1 admin    administ      3610 Aug 22  2014 .qpkg_icon.gif
   8 -rw-r--r--    1 admin    administ      4711 Aug 22  2014 .qpkg_icon_80.gif
   8 -rw-r--r--    1 admin    administ      4360 Aug 22  2014 .qpkg_icon_gray.gif
   4 -rwxr-xr-x    1 admin    administ       774 Mar 30  2016 .uninstall.sh*
   4 drwxr-xr-x    2 admin    administ      4096 Mar 25  2015 bin/
   4 drwxr-xr-x    3 admin    administ      4096 Aug 22  2014 include/
   4 drwxr-xr-x    4 admin    administ      4096 Aug 22  2014 lib/
   4 -rwxr-xr-x    1 admin    administ      2824 Aug 22  2014 python.sh*
   4 drwxr-xr-x    3 admin    administ      4096 Mar 25  2015 share/
[~] #
````

**Comment by Yannik** [comment] 2018-01-07 21:26
@kasi45 I updated renew_certificate.sh to use the default python installation if it contains the SimpleHttpServer module. However, how can we fix this problem with the different python2 paths? Is `.qpkg/Python/bin` not available at all on your qnaps except for TS-459?

**Comment by Yannik** [comment] 2018-01-07 21:33
@kasi45 PR is pull request. I think for this specific issue, it'll be fine if you simply use the german language.

**Comment by kasi45** [comment] 2018-01-07 21:42
I checked it earlier on three different NASs. The path for the python2-qpkg is not always the same. qnap builds different QPKGs for different NAS platforms! :-(
solution:

````
$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2 -V > /dev/null 2>&1 && PYTHON="$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2"
$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2 -V > /dev/null 2>&1 && PYTHON="$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2"
 
 echo $PYTHON
 ````

**Comment by kasi45** [comment] 2018-01-07 21:47
@Yannik 

your new script -> TOP!

so, now only install (create) a port 80 check and many sources of error are fixed with the new script from you.
An example of port 80 verification is included in my script. You already know this one! :-)

**Comment by Yannik** [comment] 2018-01-07 22:14
@kasi45 I've done one more update to check both src/bin/python2 and bin/python2. Can you check if this works for you?

I won't include the port 80 check for multiple reasons: If apache doesn't work due to an invalid certificate, port 80 won't be reachable. (We discussed this about using apache instead of python HTTPServer above already). Also, there is an error message about the url not being reachable by acme-tiny already and additionally, there is documentation that this is necessary in the README file

**Comment by Yannik** [comment] 2018-01-07 22:17
@kasi45 Btw, what does this do on your qnap nas'es: `pkill -f -9 "python ../HTTPServer.py"`
Does it work or is the command not available?

**Comment by kasi45** [comment] 2018-01-07 23:22
@Yannik 
No, there's been a misunderstanding here on your part. Port 80 check has nothing to do with which service is HttpServer in the script (apache or python httpserver). 
So the behavior in your current script when port 80 is closed is on the firewall:
 "renew_certificate. sh" calls the Python script "acme_certificate. sh".
There is a termination in the Python script "acme_tiny. py".
(see errorlog. txt)
The abort also prevents the following commands in the renew_certificate. sh script from being executed. The previously stopped Apache will not be restarted.
If "renew_certificate. sh" is started by Cron, nobody notices that the webserver is not running anymore.

To avoid this error, the "port 80 test" first checks if a service on port 80 is reachable from the WWW (your domain). It wouldn't matter which program is running this service on port 80. If a service exists on port 80 and can be reached from the WWW, it means that port 80 is open in your firewall.

With the previous check, there is no call of "acme_tiny. py"at all when port 80 is closed. The Apache can continue to run and only the certificate will not be renewed. And that's not so bad at the moment as if the web service is not available. 

[errorlog.txt](https://github.com/Yannik/qnap-letsencrypt/files/1610315/errorlog.txt)

**Comment by Yannik** [comment] 2018-01-07 23:31
@kasi45 Ok, I see your point about the script failure if the renewal fails. Unfortunately bash's errexit option does not come with a finally-type block for ex. starting apache again. I'll think about this a bit.

Still, if no service is running on port 80, it won't be reachable from the outside. 

Did you check my command from above?

**Comment by kasi45** [comment] 2018-01-07 23:40
@Yannik 

pkill -f -9 "python... /HTTPServer. py"
that must be from an older script. i didn't use it later.

only these lines are relevant for check port 80
when calling the script manually, the user immediately sees what's going on!
Some of it is just to make it look good. :-D

````
domainstr=$(openssl req -in letsencrypt/domain.csr -noout -text| sed -n 's/DNS://gp')
domains=(${domainstr//,/})
echo ======================================================================================================================
for i in "${domains[@]}"
do
   if [[ $(wget -q -t 1 --spider --dns-timeout 3 --connect-timeout 10  $i:80; echo $?) -eq 0 ]]; then 
	echo -e "  \033[32m OK - Port 80 open\033[0m  "$i ; 
   else 
	echo -e  "\033[31m ERROR - Port 80 closed \033[0m  " $i" not available via port 80! check portforwarding - open port 80!"
	echo ======================================================================================================================
	exit
   fi
done
echo ======================================================================================================================
````

**Comment by Yannik** [comment] 2018-01-08 13:58
@kasi45 I had a look at this part of your script, thank you :)

Can you test, if the command `pkill -f -9 "python... /HTTPServer. py"` works on your system`? I would like to change `kill $pid` to this, to ensure that all python HTTPServer instances are killed, even if a previous attempt to create a certificate failed (and the pid is different, obviously)

**Comment by kasi45** [comment] 2018-01-08 14:20
@Yannik 
I found the command "pkill" only on one of four tested QNAP NAS.
and on the one NAS, it was part of an add-on package

**Comment by Yannik** [comment] 2018-01-08 14:56
@kasi45 Okay, thank you for checking. Very annoying...

**Comment by Yannik** [comment] 2018-01-08 15:05
@kasi45 I implemented port 80 checking - can you check whether it works like this on your qnap?

**Comment by kasi45** [comment] 2018-01-08 15:06
one possibility !???
use pid file and use ">>" to enter the "pid" in the file. if there is more than one "pid" in the file due to one or more aborts of the script, then all processes are killed with these "pids".

would this work?

**Comment by Yannik** [comment] 2018-01-08 15:08
@kasi45 A pid in the file could have been reassigned to a different process - I don't think this is a good solution.

**Comment by Yannik** [comment] 2018-01-08 15:21
@kasi45 Does the port 80 checking in renew_certificate.sh work for you?

**Comment by kasi45** [comment] 2018-01-08 15:23
no, it is not OK!!!!
before "exit 1" you have to kill the httpserver and restart the apache!

**Comment by Yannik** [comment] 2018-01-08 15:30
@kasi45 Ok. I see. I thought about this some more: If the domain is not reachable - why should we care whether it has a valid certificate? I see no real benefit from this check. Due to this I decided to revert the change.

**Closed by Yannik** 2018-01-08 15:30 UTC

**Comment by kasi45** [comment] 2018-01-08 15:53
@yannik
The domain can be reached at https (port 443) No external website is offered on http (port 80). For security reasons, port 80 remains closed in the firewall.

Letsencrypt is using port 80? or has something changed? 
So before renewing the certificate, the administrator must open port 80 in the firewall manually or by script. and this is checked with the code lines. 
if the admin has slept or his script to open port 80 didn't work, the apache will be restarted and the webpages are still accessible under https (443) 
I personally control the firewall in the router via script. 

if it is not so important for you - no problem - everything else works and I can install the check myself.
Thanks for your patience!

**Comment by Yannik** [comment] 2018-01-08 15:55
@kasi45 OK - usually, renew_certificate.sh is run by cron, so I wouldn't expect users to open/close ports in the firewall each time. Normally, you'd probably want port 80 to redirect to port 443 anyway, so users can just enter "domain.com" in the URL bar. Not opening port 80 is no security improvement if you just serve a redirect, but a usability issue IMO.

Thanks for your input!
